/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    IEpWarnTriangleFilled: typeof import('~icons/ep/warn-triangle-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
